In [2]:
import pandas as pd
import numpy as np
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

import warnings
warnings.filterwarnings('ignore')

In [3]:
data = pd.read_csv('datasets/churn.csv')
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [22]:
data

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0.0,0.0,1.0,0.0,1,0.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,29.85,2505.0,0.0
1,1.0,0.0,0.0,0.0,34,1.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,3.0,56.95,1466.0,0.0
2,1.0,0.0,0.0,0.0,2,1.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,53.85,157.0,1.0
3,1.0,0.0,0.0,0.0,45,0.0,1.0,0.0,2.0,0.0,2.0,2.0,0.0,0.0,1.0,0.0,0.0,42.30,1400.0,0.0
4,0.0,0.0,0.0,0.0,2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,70.70,925.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1.0,0.0,1.0,1.0,24,1.0,2.0,0.0,2.0,0.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,84.80,1597.0,0.0
7039,0.0,0.0,1.0,1.0,72,1.0,2.0,1.0,0.0,2.0,2.0,0.0,2.0,2.0,1.0,1.0,1.0,103.20,5698.0,0.0
7040,0.0,0.0,1.0,1.0,11,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,29.60,2994.0,0.0
7041,1.0,1.0,1.0,0.0,4,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,74.40,2660.0,1.0
7042,1.0,0.0,0.0,0.0,66,1.0,0.0,1.0,2.0,0.0,2.0,2.0,2.0,2.0,2.0,1.0,0.0,105.65,5407.0,0.0

In [5]:
ord = OrdinalEncoder()
data[['gender','SeniorCitizen','Partner','Dependents','PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','Contract','PaperlessBilling','PaymentMethod','TotalCharges','Churn']] = ord.fit_transform(data[['gender','SeniorCitizen','Partner','Dependents','PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','Contract','PaperlessBilling','PaymentMethod','TotalCharges','Churn']])
data

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0.0,0.0,1.0,0.0,1,0.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,29.85,2505.0,0.0
1,1.0,0.0,0.0,0.0,34,1.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,3.0,56.95,1466.0,0.0
2,1.0,0.0,0.0,0.0,2,1.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,53.85,157.0,1.0
3,1.0,0.0,0.0,0.0,45,0.0,1.0,0.0,2.0,0.0,2.0,2.0,0.0,0.0,1.0,0.0,0.0,42.30,1400.0,0.0
4,0.0,0.0,0.0,0.0,2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,70.70,925.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1.0,0.0,1.0,1.0,24,1.0,2.0,0.0,2.0,0.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,84.80,1597.0,0.0
7039,0.0,0.0,1.0,1.0,72,1.0,2.0,1.0,0.0,2.0,2.0,0.0,2.0,2.0,1.0,1.0,1.0,103.20,5698.0,0.0
7040,0.0,0.0,1.0,1.0,11,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,29.60,2994.0,0.0
7041,1.0,1.0,1.0,0.0,4,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,74.40,2660.0,1.0
7042,1.0,0.0,0.0,0.0,66,1.0,0.0,1.0,2.0,0.0,2.0,2.0,2.0,2.0,2.0,1.0,0.0,105.65,5407.0,0.0

In [6]:
x_data = data.drop('Churn',axis=1)
y_data = data['Churn']

In [36]:
x_train,x_test,y_train,y_test = train_test_split(x_data,y_data,test_size=0.2,random_state=35)

In [37]:
x_train,val_x,y_train,val_y = train_test_split(x_train,y_train,test_size=0.2,random_state=2)

In [38]:
model = keras.Sequential([
  keras.layers.Dense(15,activation='relu',),
  keras.layers.Dropout(0.2),
  keras.layers.Dense(10,activation='relu'),
  keras.layers.Dropout(0.2),
  keras.layers.Dense(5,activation='relu'),
  keras.layers.Dropout(0.2),
  keras.layers.Dense(1,activation='sigmoid')
])

In [39]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,validation_data=(val_x,val_y),epochs=12)

Epoch 1/12
141/141 [==============================] - 2s 4ms/step - loss: 143.8044 - accuracy: 0.4149 - val_loss: 1.0098 - val_accuracy: 0.3345
Epoch 2/12
141/141 [==============================] - 0s 2ms/step - loss: 13.0166 - accuracy: 0.6297 - val_loss: 0.6645 - val_accuracy: 0.7152
Epoch 3/12
141/141 [==============================] - 0s 2ms/step - loss: 5.6544 - accuracy: 0.6603 - val_loss: 0.6728 - val_accuracy: 0.7347
Epoch 4/12
141/141 [==============================] - 0s 2ms/step - loss: 4.0304 - accuracy: 0.6745 - val_loss: 0.9774 - val_accuracy: 0.7347
Epoch 5/12
141/141 [==============================] - 0s 2ms/step - loss: 2.1700 - accuracy: 0.7053 - val_loss: 0.7642 - val_accuracy: 0.7347
Epoch 6/12
141/141 [==============================] - 0s 2ms/step - loss: 1.4988 - accuracy: 0.7122 - val_loss: 0.6133 - val_accuracy: 0.7347
Epoch 7/12
141/141 [==============================] - 0s 2ms/step - loss: 1.2616 - accuracy: 0.7138 - val_loss: 0.5939 - val_accuracy: 0.7347
Epoch 8/12
141/141 [==============================] - 0s 3ms/step - loss: 1.2904 - accuracy: 0.7182 - val_loss: 0.6162 - val_accuracy: 0.7347
Epoch 9/12
141/141 [==============================] - 0s 3ms/step - loss: 0.9152 - accuracy: 0.7191 - val_loss: 0.5889 - val_accuracy: 0.7347
Epoch 10/12
141/141 [==============================] - 0s 2ms/step - loss: 0.9828 - accuracy: 0.7224 - val_loss: 0.5908 - val_accuracy: 0.7347
Epoch 11/12
141/141 [==============================] - 0s 2ms/step - loss: 1.0385 - accuracy: 0.7204 - val_loss: 0.5874 - val_accuracy: 0.7347
Epoch 12/12
141/141 [==============================] - 0s 3ms/step - loss: 0.8598 - accuracy: 0.7262 - val_loss: 0.5846 - val_accuracy: 0.7347

In [40]:
model.evaluate(x_test,y_test)

45/45 [==============================] - 0s 2ms/step - loss: 0.5632 - accuracy: 0.7537

[0.5632491111755371, 0.753726065158844]